import {
  stockImg01,
  stockImg02,
  stockImg03,
  stockImg04,
  expireProduct01,
  expireProduct02,
  expireProduct03,
  expireProduct04,
  product6,
  product7,
  user02,
  user03,
  user05,
  user06,
  user12,
  user16,
  user21,
  user22,
  user26,
  user27
} from "../../utils/imagepath";

/** Demo sales returns — assets via Vite imports (no broken src/assets strings). */
export const salesReturnListData = [
  {
    id: "sr-1",
    returnRef: "SR-001",
    date: "12 Feb 2026",
    productName: "Lenovo IdeaPad 3",
    productImg: stockImg01,
    customer: "Carl Evans",
    customerImg: user27,
    status: "Received",
    total: "$1000",
    paid: "$1000",
    due: "$0.00",
    paymentstatus: "Paid"
  },
  {
    id: "sr-2",
    returnRef: "SR-002",
    date: "15 Feb 2026",
    productName: "Apple tablet",
    productImg: stockImg03,
    customer: "Minerva Rameriz",
    customerImg: user02,
    status: "Pending",
    total: "$1500",
    paid: "$0.00",
    due: "$1500",
    paymentstatus: "Unpaid"
  },
  {
    id: "sr-3",
    returnRef: "SR-003",
    date: "18 Feb 2026",
    productName: "Headphone",
    productImg: stockImg02,
    customer: "Robert Lamon",
    customerImg: user05,
    status: "Received",
    total: "$2000",
    paid: "$1000",
    due: "$1000",
    paymentstatus: "Overdue"
  },
  {
    id: "sr-4",
    returnRef: "SR-004",
    date: "22 Feb 2026",
    productName: "Nike Jordan",
    productImg: stockImg02,
    customer: "Mark Joslyn",
    customerImg: user03,
    status: "Received",
    total: "$1500",
    paid: "$1500",
    due: "$0.00",
    paymentstatus: "Paid"
  },
  {
    id: "sr-5",
    returnRef: "SR-005",
    date: "25 Feb 2026",
    productName: "Macbook Pro",
    productImg: stockImg04,
    customer: "Patricia Lewis",
    customerImg: user22,
    status: "Received",
    total: "$800",
    paid: "$800",
    due: "$0.00",
    paymentstatus: "Paid"
  },
  {
    id: "sr-6",
    returnRef: "SR-006",
    date: "28 Feb 2026",
    productName: "Red Premium Satchel",
    productImg: expireProduct01,
    customer: "Marsha Betts",
    customerImg: user12,
    status: "Pending",
    total: "$750",
    paid: "$0.00",
    due: "$750",
    paymentstatus: "Unpaid"
  },
  {
    id: "sr-7",
    returnRef: "SR-007",
    date: "02 Mar 2026",
    productName: "Apple Earpods",
    productImg: product7,
    customer: "Daniel Jude",
    customerImg: user06,
    status: "Received",
    total: "$1300",
    paid: "$1300",
    due: "$0.00",
    paymentstatus: "Paid"
  },
  {
    id: "sr-8",
    returnRef: "SR-008",
    date: "08 Mar 2026",
    productName: "Iphone 14 Pro",
    productImg: expireProduct02,
    customer: "Emma Bates",
    customerImg: user21,
    status: "Received",
    total: "$1100",
    paid: "$1100",
    due: "$0.00",
    paymentstatus: "Paid"
  },
  {
    id: "sr-9",
    returnRef: "SR-009",
    date: "12 Mar 2026",
    productName: "Gaming Chair",
    productImg: expireProduct03,
    customer: "Richard Fralick",
    customerImg: user16,
    status: "Pending",
    total: "$2300",
    paid: "$2300",
    due: "$0.00",
    paymentstatus: "Paid"
  },
  {
    id: "sr-10",
    returnRef: "SR-010",
    date: "18 Mar 2026",
    productName: "Borealis Backpack",
    productImg: expireProduct04,
    customer: "Michelle Robison",
    customerImg: user26,
    status: "Pending",
    total: "$1700",
    paid: "$1700",
    due: "$0.00",
    paymentstatus: "Paid"
  }
];
